[build-system]
requires = [
  "setuptools>=64.0",
  "setuptools_scm[toml]>=8.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyRestTable"
dynamic = ["version"]
description = "Format a nice table in reST (reStructuredText) from Python."
authors = [
  { name="Pete Jemian", email="prjemian+pyRestTable@gmail.com" },
]
maintainers = [
  { name="Pete Jemian", email="prjemian+pyRestTable@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.10"
keywords = ['reST', 'table', 'documentation']
license = {file = "pyRestTable/LICENSE.txt"}
classifiers = [
  "Development Status :: 6 - Mature",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "License :: Freely Distributable",
  "License :: Public Domain",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Documentation",
  "Topic :: Documentation :: Sphinx",
  "Topic :: Software Development",
  "Topic :: Software Development :: Documentation",
  "Topic :: Text Processing :: Markup",
  "Topic :: Utilities",
]
dependencies = [
  "lxml",
]

[project.optional-dependencies]
dev = [
  "coveralls",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "ruff==0.16.2",
  "setuptools-scm",
]

[project.urls]
"Homepage" = "https://prjemian.github.io/pyRestTable/"
"Bug Tracker" = "https://github.com/prjemian/pyRestTable/issues"

[tool.copyright]
copyright = "2014-2024, Pete R. Jemian"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
line-length = 115
target-version = "py311"
exclude = [
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".pytest_cache",
  ".tox",
  ".venv",
  "_build",
  "build",
  "dist",
  "docs",
]

[tool.ruff.lint]
extend-ignore = [
  "E203", # See https://github.com/PyCQA/pycodestyle/issues/373
  "E402", # module level import not at top of file (for cansas.py)
  "E501",
  "F401",  # imported but unused
  "F722", # allow Annotated[typ, some_func("some string")]
  "F811", # support typing.overload decorator
  "N999", # package name is not snake_case
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.setuptools_scm]
write_to = "pyRestTable/_version.py"
