name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  publish-pypi:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Install twine
      run: >-
        python -m
        pip install
        twine

    - name: Check package metadata
      run: >-
        twine check dist/*

    # NOTE: "Secrets" page, not "Environments"
    # NOTE: testpypi upload with versioneer only works on new tags.
    # - name: Publish distribution 📦 to Test PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
    #     verbose: true

    - name: Skip publishing 📦 to PyPI
      if: "!startsWith(github.ref, 'refs/tags')"
      run: |
        echo "Not a new tag, not publishing to PyPI."

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.10.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
